{
	"version": 1747751098,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/gui_attack-sheet0.png",
		"images/gui_jump-sheet0.png",
		"images/gui_left-sheet0.png",
		"images/gui_right-sheet0.png",
		"images/gui_up-sheet0.png",
		"images/gui_down-sheet0.png",
		"images/s_dummy-sheet0.png",
		"images/s_dummy2-sheet0.png",
		"images/s_demo-sheet0.png",
		"images/s_dummy3-sheet0.png",
		"images/s_demo2-sheet0.png",
		"images/s_character-sheet0.png",
		"images/s_character-sheet1.png",
		"images/s_enemy_slasher-sheet0.png",
		"images/s_enemy_slasher-sheet1.png",
		"images/s_player-sheet0.png",
		"images/s_health-sheet0.png",
		"images/s_movement-sheet0.png",
		"images/s_camera-sheet0.png",
		"images/s_cam_stop-sheet0.png",
		"images/s_black-sheet0.png",
		"images/s_scene-sheet0.png",
		"images/s_cam_stop2-sheet0.png",
		"images/s_cam_stop2-sheet1.png",
		"images/s_cam_stop3-sheet0.png",
		"images/s_cam_stop4-sheet0.png",
		"images/s_scene2-sheet0.png",
		"images/s_character2-sheet0.png",
		"images/s_cam_stop5-sheet0.png",
		"images/s_cam_stop5-sheet1.png",
		"images/sprite-sheet0.png",
		"media/thud 2.m4a",
		"media/thud 2.ogg",
		"media/crying_soundbible.com_1419166957.ogg",
		"media/retro jump simple a 01.ogg",
		"media/epic-motivational-music-337467.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}